server:
  port: 9191
  servlet:
    context-path: /auth-api
bezkoder.app.jwtSecret: ======================BezKoder=Spring===========================
bezkoder.app.jwtExpirationMs: 86400000
spring:
  datasource:
    url: jdbc:mysql://0.tcp.in.ngrok.io:14503/test_sec?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
  application:
    name: auth-server


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,beans
    